version: '3.7'
services:
  app:
    container_name: app
    restart: always
    build: .
    ports:
      - '5001:5001'
    depends_on:
      - mongo
    networks:
      - local

  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - './data:/data/db'
    ports:
      - '27018:27017'
    networks:
      - local

networks:
  local:
    driver: bridge




