version: '3.7'
services:
  app:
    container_name: app
    restart: always
    build: .
    ports:
      - '8080:8080'
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - './data:/data/db'
    ports:
      - '27018:27017'
